In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

## Q1

In [6]:
cut=pd.read_csv(r"C:\Users\prajw\Data Science\Assignments\3\Cutlets.csv")

In [7]:
cut.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [8]:
cut.shape

(35, 2)

In [9]:
cut.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [10]:
cut['Unit A'].std()

0.2884084841815496

In [11]:
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [23]:
tStat,pValue=stats.ttest_ind(cut['Unit A'],cut['Unit B'])

In [24]:
pValue

0.4722394724599501

In [25]:
tStat

0.7228688704678063

In [30]:
alpha=0.05

In [31]:
if pValue < alpha:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

we accept null hypothesis


## Q2

In [34]:
lab=pd.read_csv(r"C:\Users\prajw\Data Science\Assignments\3\LabTAT.csv")

In [35]:
lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [36]:
lab.shape

(120, 4)

In [37]:
t_stat,p_value=stats.f_oneway(lab.iloc[:,0],lab.iloc[:,1],lab.iloc[:,2],lab.iloc[:,3])

In [38]:
tStat

0.7228688704678063

In [39]:
p_value

2.1156708949992414e-57

In [40]:
if p_value < alpha:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

we reject null hypothesis


# Q3

In [42]:
br=pd.read_csv(r"C:\Users\prajw\Data Science\Assignments\3\BuyerRatio.csv")

In [43]:
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [44]:
chi2,pvalue,df,exp_obs = chi2_contingency(obs)

In [45]:
exp_obs

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [46]:
pvalue

0.6603094907091882

In [47]:
chi2

1.595945538661058

In [48]:
if chi2 < alpha:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

we accept null hypothesis


# Q4

In [51]:
cos=pd.read_csv(r"C:\Users\prajw\Data Science\Assignments\3\Costomer+OrderForm.csv")

In [52]:
cos.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [54]:
cos.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [55]:
cos.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [56]:
cos.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [57]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [58]:
chi2,pvalue,df,exp_obs = chi2_contingency(obs)                               

In [59]:
exp_obs

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [60]:
pvalue

0.2771020991233135

In [61]:
chi2

3.858960685820355

In [62]:
if chi2 < alpha:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

we accept null hypothesis
